"""OpenClaw 过滤中间件单元测试."""

from __future__ import annotations

import pytest
from starlette.requests import Request
from starlette.responses import Response
from starlette.testclient import TestClient

from src.api.middleware.openclaw_filter import (
    TARGET_PATH,
    OpenClawFilterMiddleware,
)


class TestOpenclawMiddlewareStateFlag:
    """中间件设置 request.state.is_openclaw 标记测试."""

    @pytest.fixture
    def app(self):
        from fastapi import FastAPI

        from src.api.routes.chat import router

        app = FastAPI()
        app.include_router(router)
        app.add_middleware(OpenClawFilterMiddleware)
        return app

    @pytest.mark.asyncio
    async def test_sets_is_openclaw_flag(self):
        from fastapi import FastAPI
        from starlette.middleware.base import BaseHTTPMiddleware

        captured_state = {}

        class CaptureMiddleware(BaseHTTPMiddleware):
            async def dispatch(self, request, call_next):
                response = await call_next(request)
                captured_state["is_openclaw"] = getattr(
                    request.state, "is_openclaw", None
                )
                return response

        app = FastAPI()
        app.add_middleware(CaptureMiddleware)
        app.add_middleware(OpenClawFilterMiddleware)

        @app.post(TARGET_PATH)
        async def handler(request: Request):
            return Response(content="ok", media_type="text/plain")

        client = TestClient(app)
        client.post(
            TARGET_PATH,
            json={
                "messages": [
                    {
                        "role": "system",
                        "content": "You are a personal assistant running inside OpenClaw.",
                    },
                    {"role": "user", "content": "你好"},
                ],
                "stream": True,
            },
        )

        assert captured_state.get("is_openclaw") is True

    @pytest.mark.asyncio
    async def test_sets_is_openclaw_false_for_non_openclaw(self):
        from fastapi import FastAPI
        from starlette.middleware.base import BaseHTTPMiddleware

        captured_state = {}

        class CaptureMiddleware(BaseHTTPMiddleware):
            async def dispatch(self, request, call_next):
                response = await call_next(request)
                captured_state["is_openclaw"] = getattr(
                    request.state, "is_openclaw", None
                )
                return response

        app = FastAPI()
        app.add_middleware(CaptureMiddleware)
        app.add_middleware(OpenClawFilterMiddleware)

        @app.post(TARGET_PATH)
        async def handler(request: Request):
            return Response(content="ok", media_type="text/plain")

        client = TestClient(app)
        client.post(
            TARGET_PATH,
            json={
                "messages": [
                    {"role": "user", "content": "你好"},
                ],
                "stream": True,
            },
        )

        assert captured_state.get("is_openclaw") is False

    @pytest.mark.asyncio
    async def test_sets_openclaw_context_when_inbound_present(self):
        """OpenClaw 请求带 Inbound Context 时, openclaw_context 被设置."""
        from fastapi import FastAPI
        from starlette.middleware.base import BaseHTTPMiddleware

        captured_state = {}

        class CaptureMiddleware(BaseHTTPMiddleware):
            async def dispatch(self, request, call_next):
                response = await call_next(request)
                captured_state["openclaw_context"] = getattr(
                    request.state, "openclaw_context", None
                )
                return response

        app = FastAPI()
        app.add_middleware(CaptureMiddleware)
        app.add_middleware(OpenClawFilterMiddleware)

        @app.post(TARGET_PATH)
        async def handler(request: Request):
            return Response(content="ok", media_type="text/plain")

        client = TestClient(app)
        client.post(
            TARGET_PATH,
            json={
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            "You are a personal assistant running inside OpenClaw.\n"
                            "## Inbound Context (trusted metadata)\n"
                            "The following JSON is generated by OpenClaw out-of-band.\n"
                            "\n"
                            "```json\n"
                            '{"account_id": "bot-1", "channel": "weixin"}\n'
                            "```"
                        ),
                    },
                    {"role": "user", "content": "你好"},
                ],
                "stream": True,
            },
        )

        ctx = captured_state.get("openclaw_context")
        assert ctx is not None
        assert ctx.account_id == "bot-1"
        assert ctx.channel == "weixin"
